import type { LocaleCode } from './locales';

export interface StatusContextCopy {
  heroIntro: string;
  saleTiming: string;
  fetchedAt: string;
  currentUnknown: string;
  historyLink: string;
  snapshotNote: string;
}

const copy: Record<LocaleCode, StatusContextCopy> = {
  de: { heroIntro: "Wir prüfen den offiziellen Ticketshop alle 15 Minuten. Aktiviere einen Alert für bestätigte Kaufbarkeit von Silver oder Gold.", saleTiming: "Dieser Tracker zeigt bestätigte Kaufbarkeit im Ticketshop. Zukünftige Verkaufstermine lassen sich daraus nicht ableiten; Ankündigungen findest du auf den offiziellen Europa-Park-Seiten.", fetchedAt: 'Status abgerufen', currentUnknown: 'Die aktuelle Verfügbarkeit kann nicht bestätigt werden.', historyLink: 'Frühere bestätigte Checks ansehen', snapshotNote: 'Letzter bestätigter Check; die Verfügbarkeit kann sich ändern.' },
  fr: { heroIntro: "Nous vérifions la billetterie officielle toutes les 15 minutes. Active une alerte lorsque Silver ou Gold est confirmé disponible à l’achat.", saleTiming: "Ce tracker affiche la disponibilité d’achat confirmée dans la billetterie. Il ne permet pas de prévoir les prochaines ventes ; consulte les annonces sur les pages officielles d’Europa-Park.", fetchedAt: 'Statut consulté', currentUnknown: 'La disponibilité actuelle ne peut pas être confirmée.', historyLink: 'Voir les vérifications précédentes confirmées', snapshotNote: 'Dernière vérification confirmée ; la disponibilité peut changer.' },
  it: { heroIntro: "Controlliamo la biglietteria ufficiale ogni 15 minuti. Attiva un avviso per la disponibilità di acquisto confermata di Silver o Gold.", saleTiming: "Questo tracker mostra la disponibilità di acquisto confermata nella biglietteria. Non consente di prevedere le prossime vendite; consulta gli annunci sulle pagine ufficiali di Europa-Park.", fetchedAt: 'Stato consultato', currentUnknown: 'La disponibilità attuale non può essere confermata.', historyLink: 'Vedi i controlli precedenti confermati', snapshotNote: 'Ultimo controllo confermato; la disponibilità può cambiare.' },
  en: { heroIntro: "We check the official ticket shop every 15 minutes. Set up an alert for confirmed availability to buy Silver or Gold.", saleTiming: "This tracker shows confirmed availability to buy in the ticket shop. It cannot predict future sale dates; check the official Europa-Park pages for announcements.", fetchedAt: 'Status requested', currentUnknown: 'Current availability cannot be confirmed.', historyLink: 'View previous confirmed checks', snapshotNote: 'Last confirmed check; availability can change.' },
  nl: { heroIntro: "We controleren de officiële ticketshop elke 15 minuten. Stel een melding in wanneer Silver of Gold aantoonbaar te koop is.", saleTiming: "Deze tracker toont bevestigde koopbaarheid in de ticketshop. Toekomstige verkoopdata zijn hieruit niet af te leiden; bekijk aankondigingen op de officiële Europa-Park-pagina’s.", fetchedAt: 'Status opgevraagd', currentUnknown: 'De huidige beschikbaarheid kan niet worden bevestigd.', historyLink: 'Bekijk eerdere bevestigde controles', snapshotNote: 'Laatste bevestigde controle; de beschikbaarheid kan veranderen.' },
  es: { heroIntro: "Comprobamos la tienda oficial cada 15 minutos. Activa una alerta cuando se confirme que Silver o Gold se puede comprar.", saleTiming: "Este tracker muestra cuándo se puede comprar de forma confirmada en la tienda. No permite predecir próximas fechas de venta; consulta los anuncios en las páginas oficiales de Europa-Park.", fetchedAt: 'Estado consultado', currentUnknown: 'No se puede confirmar la disponibilidad actual.', historyLink: 'Ver comprobaciones anteriores confirmadas', snapshotNote: 'Última comprobación confirmada; la disponibilidad puede cambiar.' },
  sv: { heroIntro: "Vi kontrollerar den officiella biljettbutiken var 15:e minut. Skapa en avisering när Silver eller Gold bekräftas vara tillgängligt att köpa.", saleTiming: "Den här trackern visar bekräftad möjlighet att köpa i biljettbutiken. Framtida försäljningsdatum kan inte förutsägas här; se meddelanden på Europa-Parks officiella sidor.", fetchedAt: 'Status kontrollerad', currentUnknown: 'Den aktuella tillgängligheten kan inte bekräftas.', historyLink: 'Visa tidigare bekräftade kontroller', snapshotNote: 'Senast bekräftade kontroll; tillgängligheten kan ändras.' },
  ro: { heroIntro: "Verificăm magazinul oficial de bilete la fiecare 15 minute. Configurează o alertă când se confirmă că Silver sau Gold poate fi cumpărat.", saleTiming: "Acest tracker arată disponibilitatea de cumpărare confirmată în magazin. Nu permite anticiparea viitoarelor date de vânzare; consultă anunțurile pe paginile oficiale Europa-Park.", fetchedAt: 'Stare solicitată', currentUnknown: 'Disponibilitatea actuală nu poate fi confirmată.', historyLink: 'Vezi verificările anterioare confirmate', snapshotNote: 'Ultima verificare confirmată; disponibilitatea se poate schimba.' },
  cs: { heroIntro: "Oficiální obchod se vstupenkami kontrolujeme každých 15 minut. Nastav upozornění, když je potvrzena možnost zakoupit Silver nebo Gold.", saleTiming: "Tento tracker zobrazuje potvrzenou možnost nákupu v obchodě. Budoucí termíny prodeje z něj nelze odvodit; oznámení najdeš na oficiálních stránkách Europa-Parku.", fetchedAt: 'Stav zjišťován', currentUnknown: 'Aktuální dostupnost nelze potvrdit.', historyLink: 'Zobrazit předchozí potvrzené kontroly', snapshotNote: 'Poslední potvrzená kontrola; dostupnost se může změnit.' },
  pl: { heroIntro: "Sprawdzamy oficjalny sklep z biletami co 15 minut. Ustaw powiadomienie, gdy potwierdzimy możliwość zakupu Silver lub Gold.", saleTiming: "Ten tracker pokazuje potwierdzoną możliwość zakupu w sklepie. Nie pozwala przewidywać przyszłych terminów sprzedaży; sprawdzaj ogłoszenia na oficjalnych stronach Europa-Parku.", fetchedAt: 'Status sprawdzony', currentUnknown: 'Nie można potwierdzić aktualnej dostępności.', historyLink: 'Zobacz poprzednie potwierdzone kontrole', snapshotNote: 'Ostatnia potwierdzona kontrola; dostępność może się zmienić.' },
  tr: { heroIntro: "Resmî bilet mağazasını her 15 dakikada bir kontrol ediyoruz. Silver veya Gold’un satın alınabildiği doğrulandığında bildirim almak için uyarı oluştur.", saleTiming: "Bu takipçi, bilet mağazasında doğrulanmış satın alma imkânını gösterir. Buradan gelecekteki satış tarihleri çıkarılamaz; duyurular için resmî Europa-Park sayfalarına bak.", fetchedAt: 'Durum sorgulandı', currentUnknown: 'Güncel uygunluk doğrulanamıyor.', historyLink: 'Önceki doğrulanmış kontrolleri görüntüle', snapshotNote: 'Son doğrulanmış kontrol; uygunluk değişebilir.' },
  da: { heroIntro: "Vi tjekker den officielle billetbutik hvert 15. minut. Opret en besked, når det bekræftes, at Silver eller Gold kan købes.", saleTiming: "Denne tracker viser bekræftet mulighed for køb i billetbutikken. Fremtidige salgsdatoer kan ikke forudsiges her; se meddelelser på Europa-Parks officielle sider.", fetchedAt: 'Status hentet', currentUnknown: 'Den aktuelle tilgængelighed kan ikke bekræftes.', historyLink: 'Se tidligere bekræftede kontroller', snapshotNote: 'Seneste bekræftede kontrol; tilgængeligheden kan ændre sig.' },
  el: { heroIntro: "Ελέγχουμε το επίσημο κατάστημα εισιτηρίων κάθε 15 λεπτά. Όρισε ειδοποίηση όταν επιβεβαιωθεί ότι μπορείς να αγοράσεις Silver ή Gold.", saleTiming: "Αυτό το εργαλείο δείχνει την επιβεβαιωμένη δυνατότητα αγοράς στο κατάστημα. Δεν προβλέπει μελλοντικές ημερομηνίες πώλησης· δες τις ανακοινώσεις στις επίσημες σελίδες του Europa-Park.", fetchedAt: 'Έλεγχος κατάστασης', currentUnknown: 'Η τρέχουσα διαθεσιμότητα δεν μπορεί να επιβεβαιωθεί.', historyLink: 'Δες προηγούμενους επιβεβαιωμένους ελέγχους', snapshotNote: 'Τελευταίος επιβεβαιωμένος έλεγχος· η διαθεσιμότητα μπορεί να αλλάξει.' },
  pt: { heroIntro: "Verificamos a bilheteira oficial a cada 15 minutos. Cria um alerta quando for confirmado que Silver ou Gold pode ser comprado.", saleTiming: "Este tracker mostra a possibilidade de compra confirmada na bilheteira. Não permite prever futuras datas de venda; consulta os anúncios nas páginas oficiais do Europa-Park.", fetchedAt: 'Estado consultado', currentUnknown: 'Não é possível confirmar a disponibilidade atual.', historyLink: 'Ver verificações anteriores confirmadas', snapshotNote: 'Última verificação confirmada; a disponibilidade pode mudar.' },
  nb: { heroIntro: "Vi sjekker den offisielle billettbutikken hvert 15. minutt. Opprett et varsel når det bekreftes at Silver eller Gold kan kjøpes.", saleTiming: "Denne trackeren viser bekreftet mulighet for kjøp i billettbutikken. Fremtidige salgsdatoer kan ikke forutsies her; se kunngjøringer på Europa-Parks offisielle sider.", fetchedAt: 'Status hentet', currentUnknown: 'Den aktuelle tilgjengeligheten kan ikke bekreftes.', historyLink: 'Se tidligere bekreftede kontroller', snapshotNote: 'Sist bekreftede kontroll; tilgjengeligheten kan endre seg.' },
  he: { heroIntro: "אנחנו בודקים את חנות הכרטיסים הרשמית כל 15 דקות. הגדר התראה כשהאפשרות לרכוש Silver או Gold מאושרת.", saleTiming: "כלי המעקב מציג אפשרות רכישה מאושרת בחנות הכרטיסים. אי אפשר להסיק מכך מועדי מכירה עתידיים; בדוק הודעות בעמודים הרשמיים של Europa-Park.", fetchedAt: 'בקשת סטטוס', currentUnknown: 'לא ניתן לאשר את הזמינות הנוכחית.', historyLink: 'הצגת בדיקות קודמות שאושרו', snapshotNote: 'הבדיקה האחרונה שאושרה; הזמינות עשויה להשתנות.' },
  hu: { heroIntro: "A hivatalos jegyboltot 15 percenként ellenőrizzük. Állíts be értesítést, amikor megerősítjük, hogy a Silver vagy Gold megvásárolható.", saleTiming: "Ez a követő a jegyboltban megerősített vásárlási lehetőséget mutatja. Ebből nem jósolhatók meg a későbbi értékesítési időpontok; a bejelentéseket az Europa-Park hivatalos oldalain találod.", fetchedAt: 'Állapot lekérdezve', currentUnknown: 'A jelenlegi elérhetőség nem erősíthető meg.', historyLink: 'Korábbi megerősített ellenőrzések megtekintése', snapshotNote: 'Utolsó megerősített ellenőrzés; az elérhetőség változhat.' },
};

export function getStatusContextCopy(locale: LocaleCode): StatusContextCopy {
  return copy[locale];
}
