import { normalizeLanguage, type SupportedLanguage } from './locales';

export interface ApiCopy {
  rate: string;
  email: string;
  pass: string;
  send: string;
  general: string;
  subscribed: string;
  invalidPassType: string;
  invalidConfirm: string;
  confirmed: string;
  invalidUnsubscribe: string;
  unsubscribed: string;
}

const apiCopy: Record<SupportedLanguage, ApiCopy> = {
  de: {
    rate: 'Zu viele Anfragen. Bitte versuche es später erneut.',
    email: 'Bitte gib eine gültige E-Mail-Adresse ein.',
    pass: 'Bitte wähle mindestens einen Pass-Typ aus.',
    send: 'E-Mail konnte nicht gesendet werden. Bitte versuche es später.',
    general: 'Ein Fehler ist aufgetreten.',
    subscribed: 'Falls die Adresse noch nicht angemeldet war, haben wir eine Bestätigungs-E-Mail geschickt.',
    invalidPassType: 'Ungültiger Pass-Typ. Erlaubt: silver, gold.',
    invalidConfirm: 'Der Bestätigungslink ist ungültig oder wurde bereits verwendet.',
    confirmed: 'E-Mail bestätigt!',
    invalidUnsubscribe: 'Der Abmelde-Link ist ungültig.',
    unsubscribed: 'Erfolgreich abgemeldet.',
  },
  fr: {
    rate: 'Trop de demandes. Veuillez réessayer plus tard.',
    email: 'Veuillez saisir une adresse e-mail valide.',
    pass: 'Veuillez sélectionner au moins un type de pass.',
    send: 'Impossible d’envoyer l’e-mail. Veuillez réessayer plus tard.',
    general: 'Une erreur est survenue.',
    subscribed: 'Si l’adresse n’était pas encore inscrite, nous avons envoyé un e-mail de confirmation.',
    invalidPassType: 'Type de pass invalide. Valeurs autorisées : silver, gold.',
    invalidConfirm: 'Le lien de confirmation est invalide ou a déjà été utilisé.',
    confirmed: 'Adresse e-mail confirmée !',
    invalidUnsubscribe: 'Le lien de désabonnement est invalide.',
    unsubscribed: 'Désabonnement effectué.',
  },
  it: {
    rate: 'Troppe richieste. Riprova più tardi.',
    email: 'Inserisci un indirizzo e-mail valido.',
    pass: 'Seleziona almeno un tipo di pass.',
    send: 'Impossibile inviare l’e-mail. Riprova più tardi.',
    general: 'Si è verificato un errore.',
    subscribed: 'Se l’indirizzo non era ancora registrato, abbiamo inviato un’e-mail di conferma.',
    invalidPassType: 'Tipo di pass non valido. Valori consentiti: silver, gold.',
    invalidConfirm: 'Il link di conferma non è valido o è già stato utilizzato.',
    confirmed: 'Indirizzo e-mail confermato!',
    invalidUnsubscribe: 'Il link di disiscrizione non è valido.',
    unsubscribed: 'Disiscrizione completata.',
  },
  en: {
    rate: 'Too many requests. Please try again later.',
    email: 'Please enter a valid email address.',
    pass: 'Please select at least one pass type.',
    send: 'The email could not be sent. Please try again later.',
    general: 'Something went wrong.',
    subscribed: 'If the address was not already subscribed, we sent a confirmation email.',
    invalidPassType: 'Invalid pass type. Allowed values: silver, gold.',
    invalidConfirm: 'The confirmation link is invalid or has already been used.',
    confirmed: 'Email confirmed!',
    invalidUnsubscribe: 'The unsubscribe link is invalid.',
    unsubscribed: 'Successfully unsubscribed.',
  },
  nl: {
    rate: 'Te veel verzoeken. Probeer het later opnieuw.',
    email: 'Vul een geldig e-mailadres in.',
    pass: 'Selecteer ten minste één type pas.',
    send: 'De e-mail kon niet worden verzonden. Probeer het later opnieuw.',
    general: 'Er is iets misgegaan.',
    subscribed: 'Als het adres nog niet was aangemeld, hebben we een bevestigingsmail gestuurd.',
    invalidPassType: 'Ongeldig type pas. Toegestane waarden: silver, gold.',
    invalidConfirm: 'De bevestigingslink is ongeldig of al gebruikt.',
    confirmed: 'E-mailadres bevestigd!',
    invalidUnsubscribe: 'De afmeldlink is ongeldig.',
    unsubscribed: 'Je bent succesvol afgemeld.',
  },
  es: {
    rate: 'Demasiadas solicitudes. Vuelve a intentarlo más tarde.',
    email: 'Introduce una dirección de correo electrónico válida.',
    pass: 'Selecciona al menos un tipo de pase.',
    send: 'No se pudo enviar el correo electrónico. Vuelve a intentarlo más tarde.',
    general: 'Algo ha salido mal.',
    subscribed: 'Si la dirección no estaba ya suscrita, hemos enviado un correo de confirmación.',
    invalidPassType: 'Tipo de pase no válido. Valores permitidos: silver, gold.',
    invalidConfirm: 'El enlace de confirmación no es válido o ya se ha utilizado.',
    confirmed: '¡Correo electrónico confirmado!',
    invalidUnsubscribe: 'El enlace de baja no es válido.',
    unsubscribed: 'Baja completada correctamente.',
  },
  sv: {
    rate: 'För många förfrågningar. Försök igen senare.',
    email: 'Ange en giltig e-postadress.',
    pass: 'Välj minst en passtyp.',
    send: 'E-postmeddelandet kunde inte skickas. Försök igen senare.',
    general: 'Något gick fel.',
    subscribed: 'Om adressen inte redan var registrerad har vi skickat ett bekräftelsemejl.',
    invalidPassType: 'Ogiltig passtyp. Tillåtna värden: silver, gold.',
    invalidConfirm: 'Bekräftelselänken är ogiltig eller har redan använts.',
    confirmed: 'E-postadressen är bekräftad!',
    invalidUnsubscribe: 'Avregistreringslänken är ogiltig.',
    unsubscribed: 'Du har avregistrerats.',
  },
  ro: {
    rate: 'Prea multe solicitări. Încearcă din nou mai târziu.',
    email: 'Introdu o adresă de e-mail validă.',
    pass: 'Selectează cel puțin un tip de abonament.',
    send: 'E-mailul nu a putut fi trimis. Încearcă din nou mai târziu.',
    general: 'A apărut o eroare.',
    subscribed: 'Dacă adresa nu era deja abonată, am trimis un e-mail de confirmare.',
    invalidPassType: 'Tip de abonament nevalid. Valori permise: silver, gold.',
    invalidConfirm: 'Linkul de confirmare este nevalid sau a fost deja folosit.',
    confirmed: 'Adresa de e-mail a fost confirmată!',
    invalidUnsubscribe: 'Linkul de dezabonare este nevalid.',
    unsubscribed: 'Dezabonare reușită.',
  },
  cs: {
    rate: 'Příliš mnoho požadavků. Zkuste to prosím později.',
    email: 'Zadejte platnou e-mailovou adresu.',
    pass: 'Vyberte alespoň jeden typ průkazu.',
    send: 'E-mail se nepodařilo odeslat. Zkuste to prosím později.',
    general: 'Něco se pokazilo.',
    subscribed: 'Pokud adresa ještě nebyla přihlášena, odeslali jsme potvrzovací e-mail.',
    invalidPassType: 'Neplatný typ průkazu. Povolené hodnoty: silver, gold.',
    invalidConfirm: 'Potvrzovací odkaz je neplatný nebo již byl použit.',
    confirmed: 'E-mailová adresa byla potvrzena!',
    invalidUnsubscribe: 'Odkaz pro odhlášení je neplatný.',
    unsubscribed: 'Odběr byl úspěšně zrušen.',
  },
  pl: {
    rate: 'Zbyt wiele żądań. Spróbuj ponownie później.',
    email: 'Podaj prawidłowy adres e-mail.',
    pass: 'Wybierz co najmniej jeden rodzaj karnetu.',
    send: 'Nie udało się wysłać wiadomości e-mail. Spróbuj ponownie później.',
    general: 'Coś poszło nie tak.',
    subscribed: 'Jeśli adres nie był jeszcze zapisany, wysłaliśmy wiadomość z prośbą o potwierdzenie.',
    invalidPassType: 'Nieprawidłowy rodzaj karnetu. Dozwolone wartości: silver, gold.',
    invalidConfirm: 'Odnośnik potwierdzający jest nieprawidłowy lub został już użyty.',
    confirmed: 'Adres e-mail został potwierdzony!',
    invalidUnsubscribe: 'Odnośnik do rezygnacji jest nieprawidłowy.',
    unsubscribed: 'Rezygnacja została przyjęta.',
  },
  tr: {
    rate: 'Çok fazla istek. Lütfen daha sonra tekrar deneyin.',
    email: 'Geçerli bir e-posta adresi girin.',
    pass: 'Lütfen en az bir kart türü seçin.',
    send: 'E-posta gönderilemedi. Lütfen daha sonra tekrar deneyin.',
    general: 'Bir sorun oluştu.',
    subscribed: 'Adres daha önce kaydedilmemişse bir onay e-postası gönderdik.',
    invalidPassType: 'Geçersiz kart türü. İzin verilen değerler: silver, gold.',
    invalidConfirm: 'Onay bağlantısı geçersiz veya daha önce kullanılmış.',
    confirmed: 'E-posta adresi onaylandı!',
    invalidUnsubscribe: 'Abonelikten çıkma bağlantısı geçersiz.',
    unsubscribed: 'Abonelikten başarıyla çıkıldı.',
  },
  da: {
    rate: 'For mange anmodninger. Prøv igen senere.',
    email: 'Indtast en gyldig e-mailadresse.',
    pass: 'Vælg mindst én korttype.',
    send: 'E-mailen kunne ikke sendes. Prøv igen senere.',
    general: 'Noget gik galt.',
    subscribed: 'Hvis adressen ikke allerede var tilmeldt, har vi sendt en bekræftelsesmail.',
    invalidPassType: 'Ugyldig korttype. Tilladte værdier: silver, gold.',
    invalidConfirm: 'Bekræftelseslinket er ugyldigt eller allerede brugt.',
    confirmed: 'E-mailadressen er bekræftet!',
    invalidUnsubscribe: 'Afmeldingslinket er ugyldigt.',
    unsubscribed: 'Du er blevet afmeldt.',
  },
  el: {
    rate: 'Πάρα πολλά αιτήματα. Δοκιμάστε ξανά αργότερα.',
    email: 'Εισαγάγετε μια έγκυρη διεύθυνση email.',
    pass: 'Επιλέξτε τουλάχιστον έναν τύπο κάρτας.',
    send: 'Δεν ήταν δυνατή η αποστολή του email. Δοκιμάστε ξανά αργότερα.',
    general: 'Κάτι πήγε στραβά.',
    subscribed: 'Αν η διεύθυνση δεν ήταν ήδη εγγεγραμμένη, στείλαμε ένα email επιβεβαίωσης.',
    invalidPassType: 'Μη έγκυρος τύπος κάρτας. Επιτρεπόμενες τιμές: silver, gold.',
    invalidConfirm: 'Ο σύνδεσμος επιβεβαίωσης δεν είναι έγκυρος ή έχει ήδη χρησιμοποιηθεί.',
    confirmed: 'Η διεύθυνση email επιβεβαιώθηκε!',
    invalidUnsubscribe: 'Ο σύνδεσμος διαγραφής δεν είναι έγκυρος.',
    unsubscribed: 'Η διαγραφή ολοκληρώθηκε με επιτυχία.',
  },
  pt: {
    rate: 'Demasiados pedidos. Tente novamente mais tarde.',
    email: 'Introduza um endereço de email válido.',
    pass: 'Selecione pelo menos um tipo de passe.',
    send: 'Não foi possível enviar o email. Tente novamente mais tarde.',
    general: 'Ocorreu um erro.',
    subscribed: 'Se o endereço ainda não estava registado, enviámos um email de confirmação.',
    invalidPassType: 'Tipo de passe inválido. Valores permitidos: silver, gold.',
    invalidConfirm: 'A ligação de confirmação é inválida ou já foi utilizada.',
    confirmed: 'Endereço de email confirmado!',
    invalidUnsubscribe: 'A ligação de cancelamento é inválida.',
    unsubscribed: 'Subscrição cancelada com sucesso.',
  },
  nb: {
    rate: 'For mange forespørsler. Prøv igjen senere.',
    email: 'Skriv inn en gyldig e-postadresse.',
    pass: 'Velg minst én passtype.',
    send: 'E-posten kunne ikke sendes. Prøv igjen senere.',
    general: 'Noe gikk galt.',
    subscribed: 'Hvis adressen ikke allerede var registrert, har vi sendt en bekreftelse på e-post.',
    invalidPassType: 'Ugyldig passtype. Tillatte verdier: silver, gold.',
    invalidConfirm: 'Bekreftelseslenken er ugyldig eller allerede brukt.',
    confirmed: 'E-postadressen er bekreftet!',
    invalidUnsubscribe: 'Avmeldingslenken er ugyldig.',
    unsubscribed: 'Du er nå avmeldt.',
  },
  he: {
    rate: 'יותר מדי בקשות. נסו שוב מאוחר יותר.',
    email: 'הזינו כתובת אימייל תקינה.',
    pass: 'בחרו לפחות סוג מנוי אחד.',
    send: 'לא ניתן היה לשלוח את הודעת האימייל. נסו שוב מאוחר יותר.',
    general: 'משהו השתבש.',
    subscribed: 'אם הכתובת עדיין לא הייתה רשומה, שלחנו הודעת אישור באימייל.',
    invalidPassType: 'סוג מנוי לא תקין. הערכים המותרים: silver, gold.',
    invalidConfirm: 'קישור האישור אינו תקין או שכבר נעשה בו שימוש.',
    confirmed: 'כתובת האימייל אושרה!',
    invalidUnsubscribe: 'הקישור לביטול ההרשמה אינו תקין.',
    unsubscribed: 'ההרשמה בוטלה בהצלחה.',
  },
  hu: {
    rate: 'Túl sok kérés. Próbáld újra később.',
    email: 'Adj meg egy érvényes e-mail-címet.',
    pass: 'Válassz legalább egy bérlettípust.',
    send: 'Az e-mailt nem sikerült elküldeni. Próbáld újra később.',
    general: 'Hiba történt.',
    subscribed: 'Ha a cím még nem volt feliratkozva, elküldtük a megerősítő e-mailt.',
    invalidPassType: 'Érvénytelen bérlettípus. Engedélyezett értékek: silver, gold.',
    invalidConfirm: 'A megerősítő link érvénytelen, vagy már felhasználták.',
    confirmed: 'Az e-mail-cím megerősítve!',
    invalidUnsubscribe: 'A leiratkozási link érvénytelen.',
    unsubscribed: 'Sikeresen leiratkoztál.',
  },
};

export function getApiCopy(value: unknown): ApiCopy {
  return apiCopy[normalizeLanguage(value)] || apiCopy.en;
}

export interface CommunityCopy {
  token: string;
  name: string;
  title: string;
  body: string;
  limit: string;
  success: string;
  general: string;
}

const communityCopy: Record<SupportedLanguage, CommunityCopy> = {
    de: {
      token: 'Ungültiger oder abgelaufener Community-Link.',
      name: 'Bitte gib einen Namen mit höchstens 50 Zeichen ein.',
      title: 'Bitte gib einen Titel mit 3 bis 100 Zeichen ein.',
      body: 'Bitte gib einen Beitrag mit 10 bis 2.000 Zeichen ein.',
      limit: 'Du hast heute schon 3 Beiträge eingereicht. Probier es morgen noch einmal.',
      success: 'Danke für deinen Tipp! Er wird geprüft und erscheint bald auf der Seite.',
      general: 'Ein Fehler ist aufgetreten.',
    },
    fr: {
      token: 'Le lien communautaire est invalide ou expiré.',
      name: 'Veuillez saisir un nom de 50 caractères maximum.',
      title: 'Veuillez saisir un titre de 3 à 100 caractères.',
      body: 'Veuillez saisir un texte de 10 à 2 000 caractères.',
      limit: 'Vous avez déjà envoyé 3 contributions aujourd’hui. Réessayez demain.',
      success: 'Merci pour votre conseil ! Il sera vérifié avant sa publication.',
      general: 'Une erreur est survenue.',
    },
    it: {
      token: 'Il link della community non è valido o è scaduto.',
      name: 'Inserisci un nome di massimo 50 caratteri.',
      title: 'Inserisci un titolo da 3 a 100 caratteri.',
      body: 'Inserisci un testo da 10 a 2.000 caratteri.',
      limit: 'Hai già inviato 3 contributi oggi. Riprova domani.',
      success: 'Grazie per il consiglio! Verrà verificato prima della pubblicazione.',
      general: 'Si è verificato un errore.',
    },
    en: {
      token: 'The community link is invalid or expired.',
      name: 'Please enter a name with no more than 50 characters.',
      title: 'Please enter a title between 3 and 100 characters.',
      body: 'Please enter a post between 10 and 2,000 characters.',
      limit: 'You have already submitted 3 posts today. Please try again tomorrow.',
      success: 'Thanks for your tip! It will be reviewed before publication.',
      general: 'Something went wrong.',
    },
    nl: {
      token: 'De communitylink is ongeldig of verlopen.',
      name: 'Vul een naam van maximaal 50 tekens in.',
      title: 'Vul een titel van 3 tot 100 tekens in.',
      body: 'Vul een bericht van 10 tot 2.000 tekens in.',
      limit: 'Je hebt vandaag al 3 bijdragen ingediend. Probeer het morgen opnieuw.',
      success: 'Bedankt voor je tip! Deze wordt beoordeeld voordat hij wordt gepubliceerd.',
      general: 'Er is iets misgegaan.',
    },
    es: {
      token: 'El enlace de la comunidad no es válido o ha caducado.',
      name: 'Introduce un nombre de 50 caracteres como máximo.',
      title: 'Introduce un título de entre 3 y 100 caracteres.',
      body: 'Introduce una publicación de entre 10 y 2.000 caracteres.',
      limit: 'Ya has enviado 3 aportaciones hoy. Vuelve a intentarlo mañana.',
      success: '¡Gracias por tu consejo! Lo revisaremos antes de publicarlo.',
      general: 'Algo ha salido mal.',
    },
    sv: {
      token: 'Community-länken är ogiltig eller har löpt ut.',
      name: 'Ange ett namn med högst 50 tecken.',
      title: 'Ange en rubrik med 3 till 100 tecken.',
      body: 'Skriv ett inlägg med 10 till 2 000 tecken.',
      limit: 'Du har redan skickat in 3 bidrag i dag. Försök igen i morgon.',
      success: 'Tack för ditt tips! Det granskas innan det publiceras.',
      general: 'Något gick fel.',
    },
    ro: {
      token: 'Linkul comunității este nevalid sau a expirat.',
      name: 'Introdu un nume de maximum 50 de caractere.',
      title: 'Introdu un titlu între 3 și 100 de caractere.',
      body: 'Introdu o postare între 10 și 2.000 de caractere.',
      limit: 'Ai trimis deja 3 contribuții astăzi. Încearcă din nou mâine.',
      success: 'Mulțumim pentru sfat! Va fi verificat înainte de publicare.',
      general: 'A apărut o eroare.',
    },
    cs: {
      token: 'Odkaz komunity je neplatný nebo vypršel.',
      name: 'Zadejte jméno o délce nejvýše 50 znaků.',
      title: 'Zadejte název o délce 3 až 100 znaků.',
      body: 'Zadejte příspěvek o délce 10 až 2 000 znaků.',
      limit: 'Dnes jste již odeslali 3 příspěvky. Zkuste to znovu zítra.',
      success: 'Děkujeme za tip! Před zveřejněním ho zkontrolujeme.',
      general: 'Něco se pokazilo.',
    },
    pl: {
      token: 'Odnośnik do społeczności jest nieprawidłowy lub wygasł.',
      name: 'Podaj nazwę o długości nie większej niż 50 znaków.',
      title: 'Podaj tytuł o długości od 3 do 100 znaków.',
      body: 'Napisz treść o długości od 10 do 2 000 znaków.',
      limit: 'Dzisiaj przesłano już 3 wpisy. Spróbuj ponownie jutro.',
      success: 'Dziękujemy za wskazówkę! Sprawdzimy ją przed publikacją.',
      general: 'Coś poszło nie tak.',
    },
    tr: {
      token: 'Topluluk bağlantısı geçersiz veya süresi dolmuş.',
      name: 'En fazla 50 karakterlik bir ad girin.',
      title: '3 ila 100 karakter arasında bir başlık girin.',
      body: '10 ila 2.000 karakter arasında bir gönderi yazın.',
      limit: 'Bugün zaten 3 katkı gönderdiniz. Yarın tekrar deneyin.',
      success: 'İpucunuz için teşekkürler! Yayınlanmadan önce incelenecek.',
      general: 'Bir sorun oluştu.',
    },
    da: {
      token: 'Community-linket er ugyldigt eller udløbet.',
      name: 'Indtast et navn på højst 50 tegn.',
      title: 'Indtast en titel på mellem 3 og 100 tegn.',
      body: 'Skriv et indlæg på mellem 10 og 2.000 tegn.',
      limit: 'Du har allerede indsendt 3 bidrag i dag. Prøv igen i morgen.',
      success: 'Tak for dit tip! Det bliver gennemgået før offentliggørelse.',
      general: 'Noget gik galt.',
    },
    el: {
      token: 'Ο σύνδεσμος της κοινότητας δεν είναι έγκυρος ή έχει λήξει.',
      name: 'Εισαγάγετε ένα όνομα έως 50 χαρακτήρες.',
      title: 'Εισαγάγετε έναν τίτλο από 3 έως 100 χαρακτήρες.',
      body: 'Γράψτε μια ανάρτηση από 10 έως 2.000 χαρακτήρες.',
      limit: 'Έχετε ήδη υποβάλει 3 αναρτήσεις σήμερα. Δοκιμάστε ξανά αύριο.',
      success: 'Ευχαριστούμε για τη συμβουλή! Θα ελεγχθεί πριν δημοσιευτεί.',
      general: 'Κάτι πήγε στραβά.',
    },
    pt: {
      token: 'A ligação à comunidade é inválida ou expirou.',
      name: 'Introduza um nome com um máximo de 50 caracteres.',
      title: 'Introduza um título entre 3 e 100 caracteres.',
      body: 'Escreva uma publicação entre 10 e 2.000 caracteres.',
      limit: 'Já enviou 3 contribuições hoje. Tente novamente amanhã.',
      success: 'Obrigado pela sua dica! Será analisada antes da publicação.',
      general: 'Ocorreu um erro.',
    },
    nb: {
      token: 'Fellesskapslenken er ugyldig eller utløpt.',
      name: 'Skriv inn et navn på maksimalt 50 tegn.',
      title: 'Skriv inn en tittel på mellom 3 og 100 tegn.',
      body: 'Skriv et innlegg på mellom 10 og 2 000 tegn.',
      limit: 'Du har allerede sendt inn 3 bidrag i dag. Prøv igjen i morgen.',
      success: 'Takk for tipset! Det blir gjennomgått før publisering.',
      general: 'Noe gikk galt.',
    },
    he: {
      token: 'הקישור לקהילה אינו תקין או שפג תוקפו.',
      name: 'הזינו שם באורך של עד 50 תווים.',
      title: 'הזינו כותרת באורך של 3 עד 100 תווים.',
      body: 'הזינו פוסט באורך של 10 עד 2,000 תווים.',
      limit: 'כבר שלחתם 3 פוסטים היום. נסו שוב מחר.',
      success: 'תודה על הטיפ! הוא ייבדק לפני הפרסום.',
      general: 'משהו השתבש.',
    },
    hu: {
      token: 'A közösségi link érvénytelen vagy lejárt.',
      name: 'Adj meg egy legfeljebb 50 karakteres nevet.',
      title: 'Adj meg egy 3–100 karakteres címet.',
      body: 'Írj egy 10–2 000 karakteres bejegyzést.',
      limit: 'Ma már 3 bejegyzést küldtél be. Próbáld újra holnap.',
      success: 'Köszönjük a tippedet! Közzététel előtt ellenőrizzük.',
      general: 'Hiba történt.',
    },
  };

export function getCommunityCopy(value: unknown): CommunityCopy {
  return communityCopy[normalizeLanguage(value)] || communityCopy.en;
}
